
// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Latitude55.Api.Models
{
    public partial class Category
    {
        

        [Required]
		[JsonProperty("id")]
        public int Id { get; set; }

        [Required]
		[JsonProperty("name")]
        public string Name { get; set; }
    } // end class

} // end Models namespace

