
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Latitude55.Api.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace Latitude55.Api
{
    [Route("api/[controller]")]
    public partial class AttributesController : Controller
    {


        /// <summary>
		/// Получить список всех атрибутов Портрета пользователя - /attributes
		/// </summary>
		/// <returns>Attribute[]</returns>
        [HttpGet]
        [Route("")]
        public virtual async Task<IActionResult> GetBase()
        {
            // Do not modify this code
            return await ((IAttributesController)this).Get();
        }
    }
}
