
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Latitude55.Api.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace Latitude55.Api
{
    [Route("api/[controller]")]
    public partial class CategoriesController : Controller
    {


        /// <summary>
		/// Получить список категорий услуг - /categories
		/// </summary>
		/// <returns>Category[]</returns>
        [HttpGet]
        [Route("")]
        public virtual async Task<IActionResult> GetBase()
        {
            // Do not modify this code
            return await ((ICategoriesController)this).Get();
        }
    }
}
