
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Latitude55.Api.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace Latitude55.Api
{
    [Route("api/[controller]")]
    public partial class PredictionController : Controller
    {


        /// <summary>
		/// Получение статистики с группировкой по Категориям услуг - /byCategories
		/// </summary>
		/// <returns>Statistics[]</returns>
        [HttpGet]
        [Route("byCategories")]
        public virtual async Task<IActionResult> GetBase()
        {
            // Do not modify this code
            return await ((IPredictionController)this).Get();
        }

        /// <summary>
		/// Получение статистики с группировкой по Услугам указанной Категории - /{category}
		/// </summary>
		/// <param name="category">ID Категории услуг</param>
		/// <returns>Statistics[]</returns>
        [HttpGet]
        [Route("byCategories/{category}")]
        public virtual async Task<IActionResult> GetByCategoryBase([FromRoute] int category)
        {
            // Do not modify this code
            return await ((IPredictionController)this).GetByCategory(category);
        }
    }
}
