
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Latitude55.Api.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace Latitude55.Api
{
    [Route("api/[controller]")]
    public partial class ServicesController : Controller
    {


        /// <summary>
		/// Получить перечень Государственных услуг - /services
		/// </summary>
		/// <returns>Service[]</returns>
        [HttpGet]
        [Route("")]
        public virtual async Task<IActionResult> GetBase()
        {
            // Do not modify this code
            return await ((IServicesController)this).Get();
        }

        /// <summary>
		/// Добавить новую услугу - /services
		/// </summary>
		/// <param name="service"></param>
        [HttpPut]
        [Route("")]
        public virtual async Task<IActionResult> PutBase(Models.Service service)
        {
            // Do not modify this code
            return await ((IServicesController)this).Put(service);
        }

        /// <summary>
		/// Получить сведения о Государственной услуге - /{id}
		/// </summary>
		/// <param name="id"></param>
		/// <returns>ServiceItem</returns>
        [HttpGet]
        [Route("{id}")]
        public virtual async Task<IActionResult> GetByIdBase([FromUri] string id)
        {
            // Do not modify this code
            return await ((IServicesController)this).GetById(id);
        }

        /// <summary>
		/// Настроить профиль Услуги - /{id}
		/// </summary>
		/// <param name="serviceitemsettings"></param>
		/// <param name="id"></param>
		/// <returns>ServiceItem</returns>
        [HttpPost]
        [Route("{id}")]
        public virtual async Task<IActionResult> PostBase([FromUri] string id, [FromBody]Models.ServiceItemSettings serviceitemsettings)
        {
            // Do not modify this code
            return await ((IServicesController)this).Post(serviceitemsettings,id);
        }

        /// <summary>
		/// Поиск Услуг по фильтру - /searches
		/// </summary>
		/// <param name="servicefilter"></param>
		/// <returns>Service[]</returns>
        [HttpPost]
        [Route("searches")]
        public virtual async Task<IActionResult> PostSearchesBase([FromBody]Models.ServiceFilter servicefilter)
        {
            // Do not modify this code
            return await ((IServicesController)this).PostSearches(servicefilter);
        }
    }
}
